"""
What leaves the machine, stated plainly.

The project's premise is that everything runs locally. A hosted provider
breaks that, and it should be a thing people choose knowingly rather than
discover afterwards.
"""

from __future__ import annotations

#: Backends that run entirely on the user's machine.
LOCAL_BACKENDS: frozenset[str] = frozenset({"llama_cpp"})


def is_local(backend_name: str) -> bool:
    return backend_name in LOCAL_BACKENDS


def data_sent_notice(backend_name: str) -> str | None:
    """
    What a hosted provider receives, or None for a local one.

    Specific about the scope, because the fear people have is that their
    whole corpus is uploaded, and the reassuring-sounding version of this
    ("we only send what is needed") does not answer that.
    """
    if is_local(backend_name):
        return None
    return (
        f"Answers are generated by {backend_name}, which runs on someone "
        f"else's computers.\n"
        f"Each question sends them: the question itself, and the passages "
        f"retrieved from your documents to answer it.\n"
        f"Your corpus is not uploaded, and the rest of your documents are "
        f"not sent.\n"
        f"Queries are billed by the provider. Set LLM_PROVIDER=llama_cpp to "
        f"keep everything local."
    )
