services:
  chroma:
    image: chromadb/chroma:0.6.3
    container_name: classmate-chroma
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - ./indexes/chroma:/chroma/chroma
    restart: unless-stopped
